export const UPDATE_USER_CHARACTERS_REQUEST_SENT = 'UPDATE_USER_CHARACTERS_REQUEST_SENT';
export const UPDATE_USER_CHARACTERS_REQUEST_OK = 'UPDATE_USER_CHARACTERS_REQUEST_OK';
export const UPDATE_USER_CHARACTERS_REQUEST_FAIL = 'UPDATE_USER_CHARACTERS_REQUEST_FAIL';

export const GET_CHARACTER_DETAILS_REQUEST_SENT = 'GET_CHARACTER_DETAILS_REQUEST_SENT';
export const GET_CHARACTER_DETAILS_REQUEST_OK = 'GET_CHARACTER_DETAILS_REQUEST_OK';
export const GET_CHARACTER_DETAILS_REQUEST_FAIL = 'GET_CHARACTER_DETAILS_REQUEST_FAIL';
